Accessibility page
DFE-Digital/early-careers-framework pull request #264
Opened 2021-04-20 09:37 UTC by goodviber

### Context
Fix a typo
### Changes proposed in this pull request

### Guidance to review

### Testing

### Review Checks
- [ ] All pages have automated accessibility checks via cypress
- [ ] All `School` queries are correctly scoped - `eligible` when they need to be

### How can I view this in a review app?

2021-04-20 09:49 UTC, ethanmills commented
What about this one: 

Current - "(Websites and Mobile Applications) (No.2) Accessibility Regulations 2018."
Should be - "(Websites and Mobile Applications) (No.{space}2) Accessibility Regulations 2018." - for screen reader to read as Number 2

2021-04-20 10:05 UTC, amazimbe commented on app/views/accessibility_statements/show.html.erb
> +      <li>zoom in up to 300% without the text spilling of the screen</li>
Shouldn't this be 'spilling off' ?

2021-04-20 11:43 UTC, callumacrae commented on .githooks/pre-commit
> +    exit 0
fyi you can just pass `--no-verify` or just `-n` to `git commit` to skip the checks and avoid having to make a change that accidentally gets committed

2021-04-22 10:08 UTC, amazimbe approved these changes
LGTM!

2021-04-22 10:11 UTC, ethanmills requested changes

2021-04-22 10:11 UTC, ethanmills commented on .githooks/pre-commit
> +    exit 0
Please revert this change

2021-04-22 10:20 UTC, goodviber commented on .githooks/pre-commit
> +    exit 0
Done

2021-04-22 10:24 UTC, ethanmills approved these changes

2021-04-22 10:27 UTC, merged