[CPDLP-2001] Improve some api error messages
DFE-Digital/early-careers-framework pull request #3584
Opened 2023-06-22 14:33 UTC by leandroalemao

### Context

- Ticket: [CPDLP-2001](https://dfedigital.atlassian.net/browse/CPDLP-2001)

Review the existing error message and update content to ensure the messages are useful and reflect the error. 

### Changes proposed in this pull request

Improve some api error messages

2023-06-22 17:15 UTC, mooktakim requested changes
Couple of minor changes

2023-06-22 17:15 UTC, mooktakim commented on config/locales/en.yml
> +  missing_course_identifier: "The  '#/course_identifier' is missing from your request. Please include a course_identifier value and try again."
There's an extra space here after "The"

2023-06-22 17:15 UTC, mooktakim commented on config/locales/en.yml
> +    missing_npq_application: "The '#/npq_application' is missing from your request. Check details and try again."
I think this should be "The entered '#/npq_application'" (to stay consistent with previous changes).

2023-06-22 19:29 UTC, cwrw reviewed
looks good past the other comments, I was wondering if there were any discussions/tickets relating to having multiple errors (where one is relevant and the others aren't) in the declaration endpoint which can confuse providers, and instead surfacing only the relevant error?

2023-06-23 16:37 UTC, mooktakim approved these changes

2023-06-28 08:38 UTC, cwrw approved these changes
⭐ !

2023-07-05 09:04 UTC, merged