SITs becoming mentors - remove separate journey
DFE-Digital/early-careers-framework pull request #3791
Opened 2023-08-08 15:59 UTC by lazydevorg

…r a mentor

### Context

- Ticket: 

### Changes proposed in this pull request

### Guidance to review

2023-08-16 15:46 UTC, Lloyd-K requested changes

2023-08-16 15:46 UTC, Lloyd-K commented on app/views/schools/add_participants/cannot_add_yourself_as_ect.html.erb
> +    <p class="govuk-body">If you are trying to add yourself as a mentor, follow the link below.</p>
```suggestion
    <p class="govuk-body">If you’re trying to add yourself as a mentor, follow the link below.</p>
```

2023-08-16 15:46 UTC, Lloyd-K commented on app/views/schools/add_participants/start_term.html.erb
> +        hint: { text: "This is when #{@wizard.full_name_or_you} will start #{@wizard.sit_mentor? ? 'your' : 'their'} #{@wizard.ect_participant? ? 'induction and begin ECF-based training' : 'ECF-based
If possible, we'd use the contraction 'you’ll' here as it's easier for users to read. Is that a problem given that we may display the user's name instead? Thanks

2023-08-21 08:43 UTC, Lloyd-K approved these changes

2023-09-06 15:08 UTC, frankieroberto approved these changes

2023-09-28 10:28 UTC, tonyheadford approved these changes
As far as I can see it looks OK, needs an OK from product before merging though to ensure the journey is correct. Be good to get this out!

2023-09-28 10:32 UTC, merged