[CST-1923] Iterations to the SIT sign-in journey
DFE-Digital/early-careers-framework pull request #3947
Opened 2023-09-06 13:43 UTC by lazydevorg

### Context

- Ticket: CST-1923

### Changes proposed in this pull request

### Guidance to review

2023-09-11 09:11 UTC, frankieroberto requested changes
Looks good! There's a few more content changes to make - I’ve left inline suggestions where I can.

The content on the `/nominations/resend-email` page has also been improved - see [prototype page](https://manage-training-for-ects-5c9ed99fc0a8.herokuapp.com/request-access) (most notably the h1 has changed) - could you also update that one please?

Thanks!

2023-09-11 09:11 UTC, frankieroberto commented on app/views/nominations/request_nomination_invite/review.html.erb
> +      We'll email an access link to
Typographic apostrophe.

```suggestion
      We’ll email an access link to
```

2023-09-11 09:11 UTC, frankieroberto commented on app/views/nominations/request_nomination_invite/success.html.erb
>      <%= govuk_panel title_text: "Your school has been sent a link", text: nil, classes: "govuk-!-margin-bottom-7" %>
We’ve removed this panel in favour of a plain h1 - see [page in the prototype](https://manage-training-for-ects-5c9ed99fc0a8.herokuapp.com/check-school-email)
```suggestion
  <h1 class="govuk-heading-xl">Check your school email</h1>
```

2023-09-11 09:11 UTC, frankieroberto commented on app/views/nominations/request_nomination_invite/success.html.erb
>      <h2 class="govuk-heading-m">What happens next</h2>
We’ve updated this content, so it's no longer a heading and a list. See [content in the prototype](https://manage-training-for-ects-5c9ed99fc0a8.herokuapp.com/check-school-email).

2023-09-11 09:11 UTC, frankieroberto commented on app/views/users/sessions/login_email_sent.html.erb
>  <% content_for :title, "Check email" %>
This should match the h1 - worth setting a variable and using it in both places maybe? (or use the locale files?)
```suggestion
<% content_for :title, "Check your email" %>
```

2023-09-11 09:11 UTC, frankieroberto commented on app/views/users/sessions/login_email_sent.html.erb
> +    <p class="govuk-body">We've sent an email to <strong><%= @login_email %></strong>.</p>
Typographic apostrophe.

```suggestion
    <p class="govuk-body">We’ve sent an email to <strong><%= @login_email %></strong>.</p>
```

2023-09-11 09:11 UTC, frankieroberto commented on app/views/users/sessions/login_email_sent.html.erb
> +      If it does not arrivate within 5 minutes, check your spam or junk folder or
Typo.
```suggestion
      If it does not arrive within 5 minutes, check your spam or junk folder or
```

2023-09-11 09:39 UTC, frankieroberto commented
Just spotted that this existing error message on the local authority page is a bit odd:

<img width="780" alt="Screenshot 2023-09-11 at 10 26 13" src="https://github.com/DFE-Digital/early-careers-framework/assets/30665/e418f3a3-8d76-457c-a968-cf7be2b3911f">

Would it be possible to change it to:

If blank
> Enter your school’s local authority

If the text entered didn't match an option from the autocomplete:
> The local authority must be one from our list

(If this is more than a quick job feel free to leave this for a future follow-up!)

2023-09-13 10:04 UTC, frankieroberto requested changes
Thanks for addressing all the feedback! 🙌 

1 last issue which is to make the title tags consistent with the updated h1 headings (sorry I missed this before).

After that we can get this shipped. 🚢 😄

2023-09-13 10:04 UTC, frankieroberto commented on app/views/nominations/request_nomination_invite/success.html.erb
> +  <h1 class="govuk-heading-xl">Check your school email</h1>
One minor thing - could you also set the `<title>` tag to the same text as this h1 please? (on line 1)

2023-09-13 10:04 UTC, frankieroberto commented on app/views/nominations/request_nomination_invite/resend_email.html.erb
> +    <h1 class="govuk-heading-l">Request access to this service</h1>
One minor thing - could you also set the <title> tag to the same text as this h1 please? (on line 1)

2023-09-13 12:44 UTC, frankieroberto approved these changes

2023-09-13 13:27 UTC, tonyheadford approved these changes

2023-09-13 13:32 UTC, merged