WIP
DFE-Digital/early-careers-framework pull request #4074
Opened 2023-09-29 16:09 UTC by ltello

### Context

- Ticket: 

### Changes proposed in this pull request

### Guidance to review

2023-10-12 11:19 UTC, tonyheadford requested changes
I think the code is fine just a few commented out bits to remove

2023-10-12 11:19 UTC, tonyheadford commented on app/forms/schools/add_participants/wizard_steps/choose_mentor_step.rb
> +          # debugger
```suggestion
```

2023-10-12 11:19 UTC, tonyheadford commented on app/forms/schools/add_participants/wizard_steps/continue_current_programme_step.rb
> +          # debugger
```suggestion
```

2023-10-12 11:19 UTC, tonyheadford commented on app/forms/schools/add_participants/wizard_steps/email_step.rb
> +          # debugger
```suggestion
```

2023-10-20 09:00 UTC, frankieroberto commented on app/views/schools/add_participants/_transferring_ect_or_mentor_answers.html.erb
> +      <% # debugger %>
```suggestion
```

2023-10-20 09:00 UTC, frankieroberto commented on app/helpers/application_helper.rb
> +      OpenStruct.new(id: "no", name: "No, they'll move to different training providers or a different training programme"),
Curly apostrophe.

```suggestion
      OpenStruct.new(id: "no", name: "No, they’ll move to different training providers or a different training programme"),
```

2023-10-20 09:01 UTC, frankieroberto commented on app/forms/schools/add_participants/transfer_wizard.rb
> +        # debugger
```suggestion
```

2023-10-25 12:13 UTC, frankieroberto approved these changes

2023-10-30 09:23 UTC, merged