Add helper class to change service fees
DFE-Digital/early-careers-framework pull request #4172
Opened 2023-10-18 15:06 UTC by ethax-ross

[Jira-2501](https://dfedigital.atlassian.net/browse/CPDLP-2501)

### Context

Occasionally we need to adjust the service fees for statements. To make this process more robust/easier to perform going forward we are going to encapsulate it in a one-off service class.

### Changes proposed in this pull request

- Add ChangeServiceFees one-off service

Add `ChangeServiceFees` class. By default a dry run will be performed and it will log out the changes to be made.

- DRY up changes to semantic versions

We currently manually change semantic version numbers in a couple of service classes. Instead of duplicating the code to increment a version we can pull in a lightweight library to do it for us.

- Extract information recording to concern

In a few of our service/lib classes that we run from the terminal its useful to be able to record changes that have/will be made so that we can inspect/record them.

Using `Rails.logger` for this is a pain from the terminal as we have to wade through all the other log messages (usually a bunch from `ActiveRecord`) or manually disable them prior to running the service class.

Add lightweight `HasRecordableInformation` concern to be able to easily record/playback information from a service class. Also adds a custom matcher to clean up the testing of this functionality.

### Guidance to review

I wasn't sure about the naming of the class; would `ChangeStatementFees` be more domain-accurate than `ChangeServiceFees`?

Example usage:

```
cpd_lead_provider = CallOffContract.last.lead_provider.cpd_lead_provider
cohort = CallOffContract.last.cohort
service = Oneoffs::ChangeServiceFees.new(cpd_lead_provider: cpd_lead_provider, cohort: cohort)
service.perform_change(date_range: 10.years.ago..Date.today, monthly_service_fee: 100, dry_run: true)
```

2023-10-19 15:05 UTC, mooktakim requested changes
It works as expected. Some suggested changes.

2023-10-20 07:04 UTC, ethax-ross commented on app/services/oneoffs/change_service_fees.rb
> +        c.save!
The `dup` method ignores timestamps so this will already be the current time

2023-10-20 07:52 UTC, ethax-ross commented on Gemfile
> +
I'll write a small service to try and encapsulate how we're versioning 👍

2023-10-20 10:26 UTC, ethax-ross commented on app/services/oneoffs/change_service_fees.rb
> +        .order(version: :desc)
I've added this logic to a new `ContractVersion` service; to keep these changes manageable I've stopped of adding a new service to find the latest `CallOffContract`, I figure we can do that when we have another use case for it.

2023-10-24 08:27 UTC, cwrw commented on app/services/finance/ecf/contract_version.rb
> +  module ECF
🌟

2023-10-24 09:13 UTC, cwrw approved these changes
nicely done!

2023-10-24 15:01 UTC, mooktakim approved these changes

2023-10-24 15:02 UTC, merged