Funded place swagger
DFE-Digital/early-careers-framework pull request #4873
Opened 2024-06-02 16:30 UTC by padv2010

### Context

- Ticket: https://dfedigital.atlassian.net/browse/CPDLP-3108

### Description

Documents API changes after adding Capping support.

2024-06-04 18:15 UTC, cwrw commented on docs/source/release-notes.html.md
> +Providers using all versions of the API can set the new funded_place field in the 'Accept an application' request body to true or false. They will also see the funded_place field in the following end
```suggestion
Providers using all versions of the API can set the new `funded_place` field in the 'Accept an application' request body to true or false. They will also see the `funded_place` field in the following endpoint response bodies:
```

2024-06-04 18:23 UTC, cwrw commented on swagger/v3/api_spec.json
> -    "/api/v3/partnerships/ecf": {
could we avoid running swaggerise on v3, and amending manually, as this is the only version that has not been fixed properly, and will change up the whole file?

2024-06-05 16:44 UTC, leandroalemao requested changes
Hi @padv2010 there're new fields added on v1/v2/v3 `npq_participant_serializer.rb` so some extra changes in the related docs are needed as well ie: https://github.com/DFE-Digital/early-careers-framework/blob/main/app/serializers/api/v1/npq_participant_serializer.rb#L26

2024-06-06 08:52 UTC, padv2010 commented
Thanks for the review @cwrw @leandroalemao 

@cwrw I have addressed both changes, 

@leandroalemao, I have updated v1 for ParticipantProfile, V2 and V3, unless I am missing something, are already there. I would appreciate some help though, because I can't add a new Schema object to V1 to support `funded_places`

2024-06-08 16:54 UTC, padv2010 commented on docs/source/release-notes.html.md
> +## ?? (pending sandbox release)
```suggestion
## 14 June 2024 (pending sandbox release)
```

2024-06-10 20:12 UTC, cwrw commented on docs/source/release-notes.html.md
> +'View a single participant's data'
```suggestion
- 'View all applications'

- 'View a specific application'

- 'View all participant data'

- 'View a single participant's data'
```

2024-06-10 20:54 UTC, cwrw reviewed
@padv2010 thank you for addressing comments. I think v3 is still missing a few places, let's chat tomorrow please. Thanks

2024-06-11 14:24 UTC, cwrw commented on swagger/v3/api_spec.json
> -    "/api/v3/partnerships/ecf": {
can we please avoid this large change, can we jump on a call?

2024-06-12 07:51 UTC, cwrw commented on swagger/v3/component_schemas/NPQApplicationAcceptAttributesRequest.yml
> -required:
Can we keep those please? as those are required for the acceptance on v3? and add the new funded place

2024-06-12 07:52 UTC, cwrw commented on swagger/v3/component_schemas/NPQApplicationAcceptRequest.yml
> -      schedule_identifier: "npq-leadership-spring"
same here

2024-06-12 09:30 UTC, cwrw approved these changes
thank you @padv2010

2024-06-12 09:52 UTC, leandroalemao approved these changes
tks @padv2010 🔝

2024-06-14 11:17 UTC, merged