Ignoring user_id on participant profiles
DFE-Digital/early-careers-framework pull request #779
Opened 2021-08-02 12:01 UTC by BroiSatse

The column is unused now

2021-08-02 14:55 UTC, ethanmills approved these changes

2021-08-02 14:56 UTC, ethanmills requested changes
Is it safe to do this on NPQ profiles?

2021-08-02 15:05 UTC, BroiSatse commented
It should be, all NPQ profiles belong to teacher_profile and (and to user through it) just as any other participation profile. The logic syncing profile with NPQ validation data record is coming in next PR. Ignored columns are pretty silly to be honest - they only remove column from attributes, but all setters and getters continue to working...

2021-08-03 09:08 UTC, ethanmills approved these changes

2021-08-03 09:10 UTC, merged